/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as ClienteMarcaProdutoRouteImport } from './routes/cliente-marca-produto'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as ImpostoRouteImport } from './routes/imposto'
import { Route as PainelPedidosRouteImport } from './routes/painel-pedidos'
import { Route as PainelPedidosClienteRouteImport } from './routes/painel-pedidos-cliente'
import { Route as VendasRouteImport } from './routes/vendas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteMarcaProdutoRoute = ClienteMarcaProdutoRouteImport.update({
  id: '/cliente-marca-produto',
  path: '/cliente-marca-produto',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpostoRoute = ImpostoRouteImport.update({
  id: '/imposto',
  path: '/imposto',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelPedidosRoute = PainelPedidosRouteImport.update({
  id: '/painel-pedidos',
  path: '/painel-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelPedidosClienteRoute = PainelPedidosClienteRouteImport.update({
  id: '/painel-pedidos-cliente',
  path: '/painel-pedidos-cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRoute
  '/cliente-marca-produto': typeof ClienteMarcaProdutoRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/imposto': typeof ImpostoRoute
  '/painel-pedidos': typeof PainelPedidosRoute
  '/painel-pedidos-cliente': typeof PainelPedidosClienteRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRoute
  '/cliente-marca-produto': typeof ClienteMarcaProdutoRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/imposto': typeof ImpostoRoute
  '/painel-pedidos': typeof PainelPedidosRoute
  '/painel-pedidos-cliente': typeof PainelPedidosClienteRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRoute
  '/cliente-marca-produto': typeof ClienteMarcaProdutoRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/imposto': typeof ImpostoRoute
  '/painel-pedidos': typeof PainelPedidosRoute
  '/painel-pedidos-cliente': typeof PainelPedidosClienteRoute
  '/vendas': typeof VendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cliente'
    | '/cliente-marca-produto'
    | '/clientes'
    | '/configuracoes'
    | '/crm'
    | '/dashboard'
    | '/estoque'
    | '/financeiro'
    | '/imposto'
    | '/painel-pedidos'
    | '/painel-pedidos-cliente'
    | '/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cliente'
    | '/cliente-marca-produto'
    | '/clientes'
    | '/configuracoes'
    | '/crm'
    | '/dashboard'
    | '/estoque'
    | '/financeiro'
    | '/imposto'
    | '/painel-pedidos'
    | '/painel-pedidos-cliente'
    | '/vendas'
  id:
    | '__root__'
    | '/'
    | '/cliente'
    | '/cliente-marca-produto'
    | '/clientes'
    | '/configuracoes'
    | '/crm'
    | '/dashboard'
    | '/estoque'
    | '/financeiro'
    | '/imposto'
    | '/painel-pedidos'
    | '/painel-pedidos-cliente'
    | '/vendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClienteRoute: typeof ClienteRoute
  ClienteMarcaProdutoRoute: typeof ClienteMarcaProdutoRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CrmRoute: typeof CrmRoute
  DashboardRoute: typeof DashboardRoute
  EstoqueRoute: typeof EstoqueRoute
  FinanceiroRoute: typeof FinanceiroRoute
  ImpostoRoute: typeof ImpostoRoute
  PainelPedidosRoute: typeof PainelPedidosRoute
  PainelPedidosClienteRoute: typeof PainelPedidosClienteRoute
  VendasRoute: typeof VendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente-marca-produto': {
      id: '/cliente-marca-produto'
      path: '/cliente-marca-produto'
      fullPath: '/cliente-marca-produto'
      preLoaderRoute: typeof ClienteMarcaProdutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imposto': {
      id: '/imposto'
      path: '/imposto'
      fullPath: '/imposto'
      preLoaderRoute: typeof ImpostoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-pedidos': {
      id: '/painel-pedidos'
      path: '/painel-pedidos'
      fullPath: '/painel-pedidos'
      preLoaderRoute: typeof PainelPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-pedidos-cliente': {
      id: '/painel-pedidos-cliente'
      path: '/painel-pedidos-cliente'
      fullPath: '/painel-pedidos-cliente'
      preLoaderRoute: typeof PainelPedidosClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClienteRoute: ClienteRoute,
  ClienteMarcaProdutoRoute: ClienteMarcaProdutoRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CrmRoute: CrmRoute,
  DashboardRoute: DashboardRoute,
  EstoqueRoute: EstoqueRoute,
  FinanceiroRoute: FinanceiroRoute,
  ImpostoRoute: ImpostoRoute,
  PainelPedidosRoute: PainelPedidosRoute,
  PainelPedidosClienteRoute: PainelPedidosClienteRoute,
  VendasRoute: VendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
